const ToolUsage = require('../models/Tool');

const processTools = {
    'text-summarizer': (input, params) => {
        const sentences = input.split(/[.!?]+/).filter(s => s.trim().length > 5);
        const maxSentences = params.length === 'short' ? 2 : params.length === 'long' ? 6 : 3;
        const summary = sentences.slice(0, maxSentences).join('. ').trim();
        const wordCount = input.split(/\s+/).length;
        const summaryWordCount = summary.split(/\s+/).length;
        const reduction = Math.round((1 - summaryWordCount / wordCount) * 100);

        return `📝 **Text Summary**\n\n---\n\n${summary}.\n\n---\n\n### Statistics:\n| Metric | Value |\n|--------|-------|\n| Original words | ${wordCount} |\n| Summary words | ${summaryWordCount} |\n| Reduction | ${reduction}% |\n| Sentences kept | ${Math.min(maxSentences, sentences.length)} of ${sentences.length} |\n\n> Summary length: **${params.length || 'medium'}**`;
    },

    'code-generator': (input, params) => {
        const lang = params.language || 'javascript';
        const templates = {
            'javascript': `// 💻 Generated JavaScript Code\n// Purpose: ${input}\n// Generated by AI Assistant Hub\n\n/**\n * ${input}\n * @returns {any} Result of the operation\n */\nfunction solution(data) {\n    // Input validation\n    if (!data) {\n        throw new Error('Data is required');\n    }\n\n    console.log('🚀 Processing:', data);\n\n    // Main logic\n    const result = {\n        input: data,\n        processed: true,\n        timestamp: new Date().toISOString()\n    };\n\n    return result;\n}\n\n// Example usage\ntry {\n    const output = solution('${input.substring(0, 30)}');\n    console.log('✅ Result:', output);\n} catch (error) {\n    console.error('❌ Error:', error.message);\n}`,
            'python': `# 🐍 Generated Python Code\n# Purpose: ${input}\n# Generated by AI Assistant Hub\n\nfrom datetime import datetime\nfrom typing import Any, Dict, Optional\n\ndef solution(data: Any) -> Dict:\n    \"\"\"\n    ${input}\n    \n    Args:\n        data: Input data to process\n    \n    Returns:\n        Dict with processed results\n    \"\"\"\n    if data is None:\n        raise ValueError('Data is required')\n    \n    print(f'🚀 Processing: {data}')\n    \n    result = {\n        'input': str(data),\n        'processed': True,\n        'timestamp': datetime.now().isoformat()\n    }\n    \n    return result\n\nif __name__ == '__main__':\n    try:\n        output = solution('${input.substring(0, 30)}')\n        print(f'✅ Result: {output}')\n    except Exception as e:\n        print(f'❌ Error: {e}')`,
            'html': `<!-- 🌐 Generated HTML Code -->\n<!-- Purpose: ${input} -->\n<!-- Generated by AI Assistant Hub -->\n\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>${input}</title>\n    <style>\n        * { margin: 0; padding: 0; box-sizing: border-box; }\n        body {\n            font-family: 'Segoe UI', sans-serif;\n            background: #0a0a1a;\n            color: #fff;\n            min-height: 100vh;\n            display: flex;\n            align-items: center;\n            justify-content: center;\n        }\n        .container {\n            max-width: 800px;\n            padding: 40px;\n            text-align: center;\n        }\n        h1 {\n            font-size: 2.5rem;\n            background: linear-gradient(135deg, #6C63FF, #00D2FF);\n            -webkit-background-clip: text;\n            -webkit-text-fill-color: transparent;\n            margin-bottom: 20px;\n        }\n        p { color: #a0a0c0; font-size: 1.1rem; line-height: 1.8; }\n        .btn {\n            display: inline-block;\n            margin-top: 20px;\n            padding: 12px 30px;\n            background: #6C63FF;\n            color: #fff;\n            border: none;\n            border-radius: 10px;\n            font-size: 1rem;\n            cursor: pointer;\n            transition: 0.3s;\n        }\n        .btn:hover { transform: translateY(-3px); box-shadow: 0 10px 20px rgba(108,99,255,0.3); }\n    </style>\n</head>\n<body>\n    <div class="container">\n        <h1>${input}</h1>\n        <p>This page was generated by AI Assistant Hub.</p>\n        <button class="btn" onclick="alert('Hello!')">Click Me</button>\n    </div>\n</body>\n</html>`,
            'typescript': `// 📘 Generated TypeScript Code\n// Purpose: ${input}\n\ninterface ProcessResult {\n    input: string;\n    processed: boolean;\n    timestamp: string;\n}\n\nfunction solution(data: string): ProcessResult {\n    if (!data) {\n        throw new Error('Data is required');\n    }\n\n    const result: ProcessResult = {\n        input: data,\n        processed: true,\n        timestamp: new Date().toISOString()\n    };\n\n    return result;\n}\n\n// Usage\nconst output = solution('${input.substring(0, 30)}');\nconsole.log(output);`,
            'css': `/* 🎨 Generated CSS Code */\n/* Purpose: ${input} */\n\n:root {\n    --primary: #6C63FF;\n    --secondary: #00D2FF;\n    --bg: #0a0a1a;\n    --text: #ffffff;\n    --muted: #a0a0c0;\n}\n\n* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\n\nbody {\n    font-family: 'Inter', 'Segoe UI', sans-serif;\n    background: var(--bg);\n    color: var(--text);\n    line-height: 1.6;\n}\n\n.container {\n    max-width: 1200px;\n    margin: 0 auto;\n    padding: 0 20px;\n}\n\n.card {\n    background: rgba(255, 255, 255, 0.05);\n    border: 1px solid rgba(255, 255, 255, 0.1);\n    border-radius: 16px;\n    padding: 24px;\n    transition: transform 0.3s, box-shadow 0.3s;\n}\n\n.card:hover {\n    transform: translateY(-5px);\n    box-shadow: 0 10px 30px rgba(108, 99, 255, 0.2);\n}\n\n.btn {\n    padding: 10px 24px;\n    background: linear-gradient(135deg, var(--primary), #5A52E0);\n    color: white;\n    border: none;\n    border-radius: 10px;\n    cursor: pointer;\n    font-weight: 600;\n    transition: 0.3s;\n}\n\n.btn:hover {\n    box-shadow: 0 5px 15px rgba(108, 99, 255, 0.4);\n}`
        };

        return `💻 **Generated ${lang.toUpperCase()} Code:**\n\n\`\`\`${lang}\n${templates[lang] || templates['javascript']}\n\`\`\`\n\n---\n\n**Language:** ${lang} | **Lines:** ~${(templates[lang] || templates['javascript']).split('\n').length}`;
    },

    'translator': (input, params) => {
        const translations = {
            'spanish': { hello: 'hola', goodbye: 'adiós', 'thank you': 'gracias', yes: 'sí', no: 'no', please: 'por favor', 'good morning': 'buenos días', 'good night': 'buenas noches', 'how are you': 'cómo estás', 'i love you': 'te amo' },
            'french': { hello: 'bonjour', goodbye: 'au revoir', 'thank you': 'merci', yes: 'oui', no: 'non', please: "s'il vous plaît", 'good morning': 'bonjour', 'good night': 'bonne nuit', 'how are you': 'comment allez-vous', 'i love you': 'je t\'aime' },
            'german': { hello: 'hallo', goodbye: 'auf wiedersehen', 'thank you': 'danke', yes: 'ja', no: 'nein', please: 'bitte', 'good morning': 'guten morgen', 'how are you': 'wie geht es ihnen', 'i love you': 'ich liebe dich' },
            'japanese': { hello: 'こんにちは (konnichiwa)', goodbye: 'さようなら (sayōnara)', 'thank you': 'ありがとう (arigatō)', yes: 'はい (hai)', no: 'いいえ (iie)', please: 'お願いします (onegaishimasu)', 'i love you': '愛してる (aishiteru)' },
            'bangla': { hello: 'হ্যালো', goodbye: 'বিদায়', 'thank you': 'ধন্যবাদ', yes: 'হ্যাঁ', no: 'না', please: 'দয়া করে', 'good morning': 'সুপ্রভাত', 'how are you': 'আপনি কেমন আছেন', 'i love you': 'আমি তোমাকে ভালোবাসি' },
            'arabic': { hello: 'مرحبا (marhaba)', goodbye: 'مع السلامة (ma\'a as-salama)', 'thank you': 'شكرا (shukran)', yes: 'نعم (na\'am)', no: 'لا (la)' },
            'hindi': { hello: 'नमस्ते (namaste)', goodbye: 'अलविदा (alvida)', 'thank you': 'धन्यवाद (dhanyavaad)', yes: 'हाँ (haan)', no: 'नहीं (nahin)', 'i love you': 'मैं तुमसे प्यार करता हूँ' },
            'korean': { hello: '안녕하세요 (annyeonghaseyo)', goodbye: '안녕히 가세요 (annyeonghi gaseyo)', 'thank you': '감사합니다 (gamsahamnida)', yes: '네 (ne)', no: '아니요 (aniyo)', 'i love you': '사랑해요 (saranghaeyo)' }
        };
        const targetLang = params.targetLanguage || 'spanish';
        const dict = translations[targetLang] || {};
        let translated = input.toLowerCase();
        for (const [eng, trans] of Object.entries(dict)) {
            translated = translated.replace(new RegExp(eng, 'gi'), trans);
        }
        return `🌐 **Translation to ${targetLang.charAt(0).toUpperCase() + targetLang.slice(1)}**\n\n| Original | Translated |\n|----------|------------|\n| ${input} | ${translated} |\n\n### Common phrases in ${targetLang}:\n${Object.entries(dict).slice(0, 5).map(([en, tr]) => `- **${en}** → ${tr}`).join('\n')}\n\n> *For production-grade translation, connect Google Translate or DeepL API*`;
    },

    'email-writer': (input, params) => {
        const tone = params.tone || 'professional';
        const templates = {
            professional: { greeting: 'Dear Sir/Madam', closing: 'Best regards', style: 'formal and professional' },
            casual: { greeting: 'Hey there! 👋', closing: 'Cheers', style: 'friendly and casual' },
            formal: { greeting: 'Respected Sir/Madam', closing: 'Yours faithfully', style: 'very formal and respectful' }
        };
        const t = templates[tone] || templates.professional;

        return `📧 **${tone.charAt(0).toUpperCase() + tone.slice(1)} Email**\n\n---\n\n**Subject:** ${input}\n\n${t.greeting},\n\nI hope this message finds you well. I am writing to you regarding **${input.toLowerCase()}**.\n\nI wanted to bring this matter to your attention and discuss the following key points:\n\n1. **Background** — A brief overview of the situation\n2. **Current Status** — Where things stand at present\n3. **Proposed Action** — Recommended next steps\n4. **Timeline** — Expected completion dates\n\nI would greatly appreciate your prompt attention to this matter. Should you need any additional information or have any questions, please do not hesitate to contact me.\n\nThank you for your time and consideration.\n\n${t.closing},\n**[Your Name]**\n*[Your Title]*\n*[Company/Organization]*\n📞 [Phone] | ✉️ [Email] | 🌐 [Website]\n\n---\n\n*Style: ${t.style}* | *Tone: ${tone}*`;
    },

    'grammar-checker': (input) => {
        const issues = [];
        if (!input.match(/^[A-Z]/)) issues.push({ type: 'Capitalization', desc: 'First letter should be capitalized', icon: '🔤' });
        if (!input.match(/[.!?]$/)) issues.push({ type: 'Punctuation', desc: 'Missing ending punctuation', icon: '❗' });
        if (input.includes('  ')) issues.push({ type: 'Spacing', desc: 'Double spaces detected', icon: '⬜' });
        if (input.match(/\bi\b/g)) issues.push({ type: 'Pronoun', desc: '"i" should be "I"', icon: '👤' });
        if (input.match(/\b(dont|cant|wont|isnt|arent|wasnt|werent|havent|hasnt|didnt|doesnt|shouldnt|wouldnt|couldnt)\b/gi)) {
            issues.push({ type: 'Contraction', desc: 'Missing apostrophe in contraction', icon: '✏️' });
        }
        if (input.split(/\s+/).length > 40 && !input.includes('.')) {
            issues.push({ type: 'Sentence Length', desc: 'Consider breaking into shorter sentences', icon: '📏' });
        }

        let corrected = input
            .replace(/^[a-z]/, c => c.toUpperCase())
            .replace(/\s+/g, ' ')
            .replace(/\bi\b/g, 'I')
            .replace(/\bdont\b/gi, "don't")
            .replace(/\bcant\b/gi, "can't")
            .replace(/\bwont\b/gi, "won't")
            .replace(/\bisnt\b/gi, "isn't")
            .replace(/\barent\b/gi, "aren't");

        if (!corrected.match(/[.!?]$/)) corrected += '.';

        const score = Math.max(0, 100 - (issues.length * 12));
        const grade = score >= 90 ? 'A+' : score >= 80 ? 'A' : score >= 70 ? 'B' : score >= 60 ? 'C' : 'D';
        const emoji = score >= 80 ? '🟢' : score >= 60 ? '🟡' : '🔴';

        return `✅ **Grammar Check Report**\n\n---\n\n### Score: ${emoji} ${score}/100 (Grade: ${grade})\n\n**Original:**\n> ${input}\n\n**Corrected:**\n> ${corrected}\n\n### Issues Found (${issues.length}):\n${issues.length > 0 ? issues.map(i => `${i.icon} **${i.type}:** ${i.desc}`).join('\n') : '✨ No major issues found! Great writing!'}\n\n### Writing Tips:\n- ✅ Use active voice\n- ✅ Keep sentences concise\n- ✅ Vary sentence length\n- ✅ Proofread before sending\n- ✅ Read aloud to catch errors`;
    },

    'mood-analyzer': (input) => {
        const positive = ['happy','great','love','wonderful','amazing','good','excellent','fantastic','joy','excited','beautiful','awesome','perfect','brilliant','outstanding','delightful','grateful','blessed','thrilled','magnificent'];
        const negative = ['sad','bad','hate','terrible','awful','angry','horrible','depressed','worst','ugly','boring','pain','miserable','disgusting','dreadful','furious','anxious','stressed','disappointed','frustrated'];

        const lowerInput = input.toLowerCase();
        let posCount = 0, negCount = 0;
        const foundPos = [], foundNeg = [];

        positive.forEach(w => { if (lowerInput.includes(w)) { posCount++; foundPos.push(w); } });
        negative.forEach(w => { if (lowerInput.includes(w)) { negCount++; foundNeg.push(w); } });

        let mood, emoji, color, advice;
        if (posCount > negCount) {
            mood = 'Positive'; emoji = '😊'; color = '🟢';
            advice = "Your text has a positive tone! Keep spreading good vibes! 🌟";
        } else if (negCount > posCount) {
            mood = 'Negative'; emoji = '😔'; color = '🔴';
            advice = "Your text has some negative tones. Remember, tough times don't last! 💪";
        } else {
            mood = 'Neutral'; emoji = '😐'; color = '🟡';
            advice = "Your text is fairly neutral. Consider adding more expressive language.";
        }

        const confidence = Math.min(100, ((Math.abs(posCount - negCount) + 1) * 20));
        const wordCount = input.split(/\s+/).length;

        return `${emoji} **Mood/Sentiment Analysis**\n\n---\n\n### Result: ${color} ${mood}\n\n| Metric | Value |\n|--------|-------|\n| Mood | **${mood}** |\n| Confidence | **${confidence}%** |\n| Word Count | ${wordCount} |\n| Positive Words | ${posCount} |\n| Negative Words | ${negCount} |\n\n${foundPos.length > 0 ? `**Positive words found:** ${foundPos.join(', ')}` : ''}\n${foundNeg.length > 0 ? `**Negative words found:** ${foundNeg.join(', ')}` : ''}\n\n### 💡 Insight:\n> ${advice}\n\n---\n*Text analyzed: "${input.substring(0, 80)}${input.length > 80 ? '...' : ''}"*`;
    },

    'recipe-generator': (input) => {
        return `🍳 **Recipe: Delicious ${input}**\n\n---\n\n### 📋 Ingredients:\n- 🥘 ${input} (main, 500g)\n- 🫒 2 tbsp olive oil\n- 🧄 3 cloves garlic, minced\n- 🧅 1 large onion, diced\n- 🧂 Salt and pepper to taste\n- 🌿 Fresh herbs (parsley, basil, cilantro)\n- 🍋 1 lemon (for zest and juice)\n- 🫑 1 bell pepper, diced\n- 🍅 2 tomatoes, chopped\n\n### 👨‍🍳 Instructions:\n\n**Step 1** — *Prep (10 min)*\nWash and prepare all ingredients. Dice vegetables, mince garlic.\n\n**Step 2** — *Sauté (5 min)*\nHeat olive oil in a large pan over medium heat. Add garlic and onions, cook until golden.\n\n**Step 3** — *Cook (15 min)*\nAdd ${input.toLowerCase()} to the pan. Season with salt and pepper. Cook thoroughly.\n\n**Step 4** — *Add vegetables (5 min)*\nAdd bell pepper and tomatoes. Stir well and cook for 5 more minutes.\n\n**Step 5** — *Finish (2 min)*\nAdd fresh herbs and lemon juice. Toss everything together.\n\n**Step 6** — *Serve* 🎉\nPlate beautifully and serve hot!\n\n---\n\n| Info | Details |\n|------|--------|\n| ⏱️ Prep Time | 10 minutes |\n| 🔥 Cook Time | 25 minutes |\n| 🍽️ Serves | 3-4 people |\n| 📊 Difficulty | Easy |\n\n*Bon Appétit! 🎉*`;
    },

    'quiz-generator': (input) => {
        return `📝 **Quiz: ${input}**\n\n---\n\n### Question 1: (Multiple Choice)\nWhat is the primary concept behind ${input}?\n\n- A) It's a theoretical framework\n- B) It's a practical methodology \n- C) It's a combination of both\n- D) None of the above\n\n**Correct:** C ✅\n\n---\n\n### Question 2: (True/False)\n${input} is widely used in modern applications.\n\n- A) True ✅\n- B) False\n\n---\n\n### Question 3: (Short Answer)\nExplain in 2-3 sentences what ${input} means to you.\n\n> *[Write your answer here]*\n\n---\n\n### Question 4: (Multiple Choice)\nWhich of the following best relates to ${input}?\n\n- A) Technology and innovation\n- B) Art and creativity\n- C) Science and research \n- D) All of the above ✅\n\n---\n\n### Question 5: (Essay)\nDiscuss the importance of ${input} in today's world. Provide at least one real-world example.\n\n> *[Write your essay here]*\n\n---\n\n📊 **Quiz Stats:**\n| Info | Value |\n|------|-------|\n| Total Questions | 5 |\n| MC Questions | 2 |\n| True/False | 1 |\n| Short Answer | 1 |\n| Essay | 1 |\n| Total Points | 50 |\n| Pass Mark | 30 |`;
    },

    'image-generator': (input) => {
        const styles = ['Digital Art', 'Oil Painting', 'Watercolor', 'Photography', 'Anime', '3D Render', 'Pixel Art', 'Sketch'];
        const randomStyle = styles[Math.floor(Math.random() * styles.length)];

        return `🖼️ **Image Generation Request**\n\n---\n\n### 📸 Prompt:\n> "${input}"\n\n### 🎨 Style: ${randomStyle}\n\n### Visual Description:\nImagine a stunning **${randomStyle.toLowerCase()}** depicting: *${input}*\n\nThe composition features:\n- **Foreground:** Detailed subject matter with rich textures\n- **Background:** Complementary environment with atmospheric depth\n- **Lighting:** Dynamic lighting with natural shadows\n- **Color Palette:** Harmonious colors that evoke the intended mood\n- **Details:** Fine intricate details throughout the piece\n\n### 🔧 Generation Settings:\n| Setting | Value |\n|---------|-------|\n| Style | ${randomStyle} |\n| Resolution | 1024×1024 |\n| Quality | High |\n| Seed | ${Math.floor(Math.random() * 99999)} |\n\n### 📌 To enable actual image generation:\n1. Get an API key from **OpenAI (DALL-E)** or **Stability AI**\n2. Add the key in **Settings → API Configuration**\n3. Generated images will appear here!\n\n> *Currently showing text description. Connect an image API for actual generation.*`;
    }
};

exports.useTool = async (req, res) => {
    try {
        const { toolName } = req.params;
        const { input, parameters } = req.body;

        if (!input) {
            return res.status(400).json({ success: false, message: 'Please provide input' });
        }

        const processor = processTools[toolName];
        if (!processor) {
            return res.status(400).json({ success: false, message: 'Invalid tool name' });
        }

        const output = processor(input, parameters || {});

        const toolUsage = await ToolUsage.create({
            user: req.user._id,
            toolName,
            input,
            output,
            parameters: parameters || {}
        });

        res.status(200).json({
            success: true,
            result: { id: toolUsage._id, toolName, output, createdAt: toolUsage.createdAt }
        });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

exports.getToolHistory = async (req, res) => {
    try {
        const { toolName, page = 1, limit = 20 } = req.query;
        const query = { user: req.user._id };
        if (toolName) query.toolName = toolName;

        const history = await ToolUsage.find(query).sort({ createdAt: -1 }).limit(limit * 1).skip((page - 1) * limit);
        const total = await ToolUsage.countDocuments(query);

        res.status(200).json({ success: true, count: history.length, total, history });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

exports.getTools = async (req, res) => {
    const tools = [
        { name: 'text-summarizer', icon: '📝', title: 'Text Summarizer', description: 'Summarize long texts into key points', category: 'writing' },
        { name: 'code-generator', icon: '💻', title: 'Code Generator', description: 'Generate code in JS, Python, HTML, TS, CSS', category: 'coding' },
        { name: 'translator', icon: '🌐', title: 'Translator', description: 'Translate to 8+ languages', category: 'language' },
        { name: 'email-writer', icon: '📧', title: 'Email Writer', description: 'Generate professional emails with different tones', category: 'writing' },
        { name: 'grammar-checker', icon: '✅', title: 'Grammar Checker', description: 'Check and fix grammar with scoring', category: 'writing' },
        { name: 'mood-analyzer', icon: '😊', title: 'Mood Analyzer', description: 'Analyze sentiment and mood of text', category: 'analysis' },
        { name: 'recipe-generator', icon: '🍳', title: 'Recipe Generator', description: 'Generate detailed recipes from ingredients', category: 'lifestyle' },
        { name: 'quiz-generator', icon: '📝', title: 'Quiz Generator', description: 'Create quizzes on any topic', category: 'education' },
        { name: 'image-generator', icon: '🖼️', title: 'Image Generator', description: 'Generate image descriptions (API key needed for actual images)', category: 'creative' }
    ];
    res.status(200).json({ success: true, tools });
};